In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

IMPORT DATA

In [3]:
raw_data=np.genfromtxt('E:\\DataScience\\Phyton\\Numpy\\loan-data.csv',delimiter = ';', skip_header =1,autostrip=True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Missing Value

In [4]:
np.isnan(raw_data).sum()

88005

In [5]:
temp_fill = np.nanmax(raw_data)+1
temp_mean = np.nanmean(raw_data, axis = 0)

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\314499198.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data, axis = 0)


In [6]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temp_stats = np.array([np.nanmin(raw_data,axis =0),
                  temp_mean,
                  np.nanmax(raw_data,axis =0)])
temp_stats

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\1214094180.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data,axis =0),
C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\1214094180.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data,axis =0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

Splitting Dataset

In [8]:
column_strings=np.argwhere(np.isnan(temp_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [9]:
column_numerics=np.argwhere(np.isnan(temp_mean)==False).squeeze()
column_numerics

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

reimporting data

In [10]:
loan_data_strings=np.genfromtxt('E:\\DataScience\\Phyton\\Numpy\\loan-data.csv',
                               delimiter = ';', 
                               skip_header =1,
                               autostrip=True, 
                               usecols = column_strings,
                               dtype = np.str)
loan_data_strings

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\3712675865.py:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [11]:
loan_data_numerics=np.genfromtxt('E:\\DataScience\\Phyton\\Numpy\\loan-data.csv',
                               delimiter = ';', 
                               skip_header =1,
                               autostrip=True, 
                               usecols = column_numerics,
                                filling_values = temp_fill)
loan_data_numerics

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

Loading Header

In [12]:
header_full = np.genfromtxt('E:\\DataScience\\Phyton\\Numpy\\loan-data.csv',
                            delimiter = ';', 
                            skip_footer =raw_data.shape[0],
                            dtype = np.str)
header_full

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\4071392537.py:4: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [13]:
header_strings, header_numerics = header_full[column_strings],header_full[column_numerics] 
header_strings, header_numerics

(array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
        'addr_state'], dtype='<U19'),
 array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19'))

CheckPoint

In [14]:
def checkpoint(filename, checkpoint_header, checkpoint_data):
    np.savez(filename, header =checkpoint_header, data =checkpoint_data)
    checkpoint_variable = np.load(filename + ".npz")
    return (checkpoint_variable)

In [15]:
checkpoint_test = checkpoint("checkpoint_test",header_strings,loan_data_strings)

In [16]:
checkpoint_test["data"]

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

Manipulating Strings

In [17]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
header_strings[0]='issue_date'

Issue Date

In [19]:
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [20]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [21]:
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],'-15')

In [22]:
months = np.array(['0','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [23]:
np.size(months)

13

In [24]:
for i in range(13):
    loan_data_strings[:,0]= np.where(loan_data_strings[:,0] == months[i],
                                    i,
                                    loan_data_strings[:,0])
loan_data_strings[:,0]

array(['5', '', '9', ..., '6', '4', '12'], dtype='<U69')

In [25]:
loan_data_strings[:,0]=np.where(loan_data_strings[:,0]=='',0,loan_data_strings[:,0])

In [26]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [27]:
loan_data_strings[:,0]

array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69')

Loan Grade

In [28]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [29]:
loan_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [30]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [31]:
np.unique(loan_data_strings[:,1]).size

9

In [32]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [33]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)
loan_data_strings[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

In [34]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [35]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

Term

In [36]:
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [37]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [38]:
header_strings[2]='term_months'
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [39]:
loan_data_strings[:,2]= np.chararray.strip(loan_data_strings[:,2], ' months')
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [40]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                 60,
                                 loan_data_strings[:,2])

In [41]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

Grading

In [42]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [43]:
loan_data_strings[:,3:5]

array([['C', 'C3'],
       ['A', 'A5'],
       ['B', 'B5'],
       ...,
       ['A', 'A5'],
       ['D', 'D2'],
       ['A', 'A4']], dtype='<U69')

In [44]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [45]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

Filling SubGrade

In [46]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == ' ') & (loan_data_strings[:,3] == i),
                                      i +'5',
                                      loan_data_strings[:,4])

In [47]:
np.unique(loan_data_strings[:,4], return_counts = True, return_index = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  31,  102,   23,  190,   19,    1,   44,   21,   59,   33,    2,   11,    9,    0,    5,
          83,   10,   85,   30,   55,   15,   93,   76,    4,   16,   37,   34,   50,   86,    6,
        1220,  208,  447, 1138, 1732,  602], dtype=int64),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

In [48]:
loan_data_strings[:,4]= np.where(loan_data_strings[:,4] == '',
                                'H1',
                                loan_data_strings[:,4])

In [49]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

Deleting Column Grade

In [50]:
loan_data_strings = np.delete(loan_data_strings,3,axis=1)

In [51]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [52]:
header_strings = np.delete(header_strings,3)

In [53]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

Converting SubGrade

In [54]:
np.unique(loan_data_strings[:,3]).shape

(36,)

In [55]:
keys = list(np.unique(loan_data_strings[:,3]))
values = list(range(1,np.unique(loan_data_strings[:,3]).shape[0]+1))
dict_subgrade = dict(zip(keys,values))
dict_subgrade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [56]:
for i in list(np.unique(loan_data_strings[:,3])):
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                    dict_subgrade[i],
                                    loan_data_strings[:,3])

Verification

In [57]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [58]:
loan_data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [59]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [60]:
loan_data_strings[:,4]=np.where((loan_data_strings[:,4] =='') | (loan_data_strings[:,4] == 'Not Verified'),0,1)

In [61]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

URL

In [62]:
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [63]:
loan_data_strings[:,5] = np.chararray.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [64]:
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [65]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [66]:
loan_data_numerics[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [67]:
loan_data_strings[:,5].astype(dtype= np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [68]:
loan_data_numerics[:,0].astype(dtype= np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [69]:
np.array_equal(loan_data_strings[:,5].astype(dtype= np.int32),loan_data_numerics[:,0].astype(dtype= np.int32))

True

In [70]:
loan_data_strings = np.delete(loan_data_strings, 5, axis=1)

In [71]:
loan_data_strings

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [72]:
header_strings = np.delete(header_strings, 5)

In [73]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

STATE ADDRESSES

In [74]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [75]:
np.unique(loan_data_strings[:,5], return_counts = True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [76]:
states_names, states_count = np.unique(loan_data_strings[:,5], return_counts = True)
states_names, states_count

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [77]:
states_count_sorted = np.argsort(-states_count)

In [78]:
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [79]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5]=='',0,loan_data_strings[:,5])

In [80]:
np.unique(loan_data_strings[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [81]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [82]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_west),1,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_south),2,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_midwest),3,loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_east),4,loan_data_strings[:,5])

In [83]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

##Converting Strings to Numericals

In [84]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [85]:
loan_data_strings = loan_data_strings.astype(dtype=np.int)

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\3219970070.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings = loan_data_strings.astype(dtype=np.int)


In [86]:
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

CheckPoint Strings

In [87]:
Checkpoint_strings = checkpoint("checkpoint_strings", header_strings, loan_data_strings)

In [88]:
Checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [89]:
Checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [90]:
np.array_equal(Checkpoint_strings['data'], loan_data_strings)

True

Numeric Data Manipulation

In [91]:
header_numerics

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [92]:
loan_data_numerics

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [93]:
np.isnan(loan_data_numerics).sum()

0

ID

In [94]:
temp_fill

68616520.0

In [95]:
np.isin(loan_data_numerics[:,0],temp_fill).sum()

0

In [96]:
loan_data_numerics[:,0].astype(np.int)

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\2608702303.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_numerics[:,0].astype(np.int)


array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [97]:
loan_data_numerics[:,0] = loan_data_numerics[:,0].astype(dtype=np.int)
loan_data_numerics

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\1321740057.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_numerics[:,0] = loan_data_numerics[:,0].astype(dtype=np.int)


array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

Temporary Stats

In [98]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [99]:
temp_stats[:,column_numerics]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [100]:
header_numerics

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

Substituting Funded Amount, Max Value

In [101]:
np.isin(loan_data_numerics[:,2],temp_fill).sum()

500

In [102]:
np.argwhere(np.isin(loan_data_numerics[:,2],temp_fill))

array([[  57],
       [  58],
       [  59],
       [  85],
       [ 100],
       [ 145],
       [ 161],
       [ 218],
       [ 236],
       [ 240],
       [ 262],
       [ 279],
       [ 297],
       [ 303],
       [ 306],
       [ 365],
       [ 374],
       [ 377],
       [ 397],
       [ 427],
       [ 468],
       [ 481],
       [ 498],
       [ 544],
       [ 556],
       [ 568],
       [ 576],
       [ 580],
       [ 588],
       [ 635],
       [ 669],
       [ 734],
       [ 742],
       [ 750],
       [ 789],
       [ 794],
       [ 798],
       [ 809],
       [ 818],
       [ 819],
       [ 840],
       [ 846],
       [ 860],
       [ 864],
       [ 871],
       [ 917],
       [ 958],
       [ 973],
       [ 979],
       [ 985],
       [ 994],
       [1005],
       [1007],
       [1075],
       [1085],
       [1088],
       [1149],
       [1160],
       [1178],
       [1186],
       [1199],
       [1203],
       [1204],
       [1215],
       [1226],
       [1230],
       [12

In [103]:
loan_data_numerics[:,2]= np.where(loan_data_numerics[:,2] == temp_fill,
                                 temp_stats[0,column_numerics[2]],
                                 loan_data_numerics[:,2])

In [104]:
np.isin(loan_data_numerics[:,2],temp_fill).sum()

0

In [105]:
header_numerics

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

'loan_amnt', 'int_rate', 'installment', 'total_pymnt' Maxm Value

In [106]:
for i in [1,3,4,5]:
    loan_data_numerics[:,i]= np.where(loan_data_numerics[:,i] == temp_fill,
                                 temp_stats[0,column_numerics[i]],
                                 loan_data_numerics[:,i])

In [107]:
np.isin(loan_data_numerics,temp_fill).sum()

0

USD-Euro Conversion

In [108]:
np.genfromtxt("E:\\DataScience\\Phyton\\Numpy\\EUR-USD.CSV", delimiter =',', autostrip= True)

array([[ nan,  nan,  nan,  nan,  nan],
       [1.21, 1.21, 1.11, 1.13, 0.  ],
       [1.13, 1.15, 1.12, 1.12, 0.  ],
       [1.12, 1.12, 1.05, 1.08, 0.  ],
       [1.07, 1.12, 1.05, 1.11, 0.  ],
       [1.12, 1.15, 1.08, 1.1 , 0.  ],
       [1.1 , 1.14, 1.09, 1.12, 0.  ],
       [1.11, 1.12, 1.08, 1.09, 0.  ],
       [1.1 , 1.17, 1.09, 1.13, 0.  ],
       [1.12, 1.15, 1.11, 1.13, 0.  ],
       [1.12, 1.15, 1.09, 1.1 , 0.  ],
       [1.1 , 1.11, 1.06, 1.06, 0.  ],
       [1.06, 1.11, 1.05, 1.09, 0.  ]])

In [109]:
np.genfromtxt("E:\\DataScience\\Phyton\\Numpy\\EUR-USD.CSV", delimiter =',', autostrip= True, dtype=np.str)

C:\Users\Patience\AppData\Local\Temp\ipykernel_15228\725687023.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.genfromtxt("E:\\DataScience\\Phyton\\Numpy\\EUR-USD.CSV", delimiter =',', autostrip= True, dtype=np.str)


array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [110]:
Eur_Usd = np.genfromtxt("E:\\DataScience\\Phyton\\Numpy\\EUR-USD.CSV", delimiter =',', autostrip= True, skip_header=1,usecols=3)
Eur_Usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [111]:
Eur_Usd.shape

(12,)

In [112]:
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [113]:
exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                            Eur_Usd[i-1],
                            exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(Eur_Usd),
                         exchange_rate)

In [114]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [115]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [116]:
loan_data_numerics=np.hstack((loan_data_numerics,exchange_rate))

In [117]:
loan_data_numerics

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,       31.42,     2185.64,        1.12],
       [46154151.  ,     1000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [118]:
header_numerics = np.concatenate((header_numerics, np.array(['exchange_rate'])))
header_numerics

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

Converting Values

In [119]:
column_dollars = np.array([1,2,4,5])
column_dollars

array([1, 2, 4, 5])

In [120]:
for i in column_dollars:
    loan_data_numerics = np.hstack((loan_data_numerics,np.reshape(loan_data_numerics[:,i]/loan_data_numerics[:,6],(10000,1))))

In [121]:
loan_data_numerics.shape

(10000, 11)

Header Additional

In [122]:
header_add = np.array([column_name + '_Eur' for column_name in header_numerics[column_dollars]])

In [123]:
header_add

array(['loan_amnt_Eur', 'funded_amnt_Eur', 'installment_Eur', 'total_pymnt_Eur'], dtype='<U15')

In [124]:
header_numerics = np.concatenate((header_numerics,header_add))
header_numerics

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_Eur', 'funded_amnt_Eur', 'installment_Eur', 'total_pymnt_Eur'], dtype='<U19')

In [125]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [126]:
header_numerics = header_numerics[column_index_order]
header_numerics

array(['id', 'loan_amnt', 'loan_amnt_Eur', 'funded_amnt', 'funded_amnt_Eur', 'int_rate',
       'installment', 'installment_Eur', 'total_pymnt', 'total_pymnt_Eur', 'exchange_rate'],
      dtype='<U19')

In [127]:
loan_data_numerics=loan_data_numerics[:,column_index_order]

In [128]:
loan_data_numerics.shape

(10000, 11)

Interest Rate

In [129]:
loan_data_numerics[:,5]=loan_data_numerics[:,5]/100

In [130]:
loan_data_numerics[:,5]

array([0.13, 0.06, 0.06, ..., 0.06, 0.17, 0.06])

CheckPoint 2: numeric

In [131]:
Checkpoint_numerics = checkpoint("checkpoint_numerics", header_numerics, loan_data_numerics)

In [132]:
Checkpoint_numerics['header']

array(['id', 'loan_amnt', 'loan_amnt_Eur', 'funded_amnt', 'funded_amnt_Eur', 'int_rate',
       'installment', 'installment_Eur', 'total_pymnt', 'total_pymnt_Eur', 'exchange_rate'],
      dtype='<U19')

Creating Complete Dataset

In [133]:
Checkpoint_numerics['header'].shape

(11,)

In [134]:
Checkpoint_strings['header'].shape

(6,)

In [135]:
Checkpoint_numerics['data'].shape

(10000, 11)

In [136]:
Checkpoint_strings['data'].shape

(10000, 6)

In [137]:
loan_data = np.hstack((Checkpoint_numerics['data'],Checkpoint_strings['data']))

In [138]:
loan_data.shape

(10000, 17)

In [139]:
loan_header = np.concatenate((Checkpoint_numerics['header'],Checkpoint_strings['header']))
loan_header

array(['id', 'loan_amnt', 'loan_amnt_Eur', 'funded_amnt', 'funded_amnt_Eur', 'int_rate',
       'installment', 'installment_Eur', 'total_pymnt', 'total_pymnt_Eur', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [140]:
loan_header.shape

(17,)

Rearranging

In [141]:
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [142]:
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [143]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [144]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       36.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

Combining All Data

In [145]:
loan_data_preprocessed = np.vstack((np.reshape(loan_header,(1,17)),loan_data))

In [146]:
loan_data_preprocessed

array([['id', 'loan_amnt', 'loan_amnt_Eur', ..., 'sub_grade', 'verification_status', 'addr_state'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '36.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

Saving Dataset

np.savetxt('E:\\DataScience\\Phyton\\Numpy\\loan_data_preprocessed.csv',
           loan_data_preprocessed,
           fmt = '%s',
           delimiter =',')

In [148]:
loan_data_preprocessed[0]

array(['id', 'loan_amnt', 'loan_amnt_Eur', 'funded_amnt', 'funded_amnt_Eur', 'int_rate',
       'installment', 'installment_Eur', 'total_pymnt', 'total_pymnt_Eur', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U32')

In [150]:
loan_data_preprocessed.shape

(10001, 17)

***Data Analysis***

In [169]:
import pandas as pd

In [171]:
loan_1 =pd.read_csv('E:\\DataScience\\Phyton\\Numpy\\loan_data_preprocessed.csv')
loan_1.head(5)

id  loan_amnt  loan_amnt_Eur  funded_amnt  funded_amnt_Eur  int_rate  \
0  373332.0     9950.0    9038.082814       1000.0       908.350032    0.1825   
1  575239.0    12000.0   10900.200379      12000.0     10900.200379    0.2099   
2  707689.0    10000.0    8924.299805      10000.0      8924.299805    0.1366   
3  709828.0    27200.0   24707.120859      27200.0     24707.120859    0.0600   
4  849994.0    11400.0   10526.076489      11400.0     10526.076489    0.0600   

   installment  installment_Eur  total_pymnt  total_pymnt_Eur  exchange_rate  \
0       360.97       327.887111      1072.82       974.496081       1.100897   
1       324.58       294.832253       959.75       871.788943       1.100897   
2       340.13       303.542209      3726.25      3325.417215       1.120536   
3       553.87       503.107832         0.00         0.000000       1.100897   
4       376.09       347.258957      3753.60      3465.849185       1.083025   

   issue_date  loan_status  term_months  sub_grade  verification_status  \
0        10.0          1.0         36.0       21.0                  0.0   
1        10.0          1.0         60.0       36.0                  1.0   
2         2.0          1.0         36.0       13.0                  1.0   
3        10.0          1.0         60.0        6.0                  0.0   
4         3.0          0.0         36.0       10.0                  0.0   

   addr_state  
0         1.0  
1         2.0  
2         0.0  
3         4.0  
4         1.0

In [180]:
loan_1['loan_amnt'].sum()

145597900.0

In [182]:
loan_1.iloc[:,1].mean()

14559.79

In [183]:
loan_1.iloc[:,1].min()

1000.0

In [185]:
loan_1.iloc[:,1].max()

35000.0

In [189]:
loan_1.groupby(['issue_date']).sum().iloc[:,1]

issue_date
0.0      7553700.0
1.0     11417500.0
2.0      7911775.0
3.0      8048875.0
4.0     10796100.0
5.0     11031325.0
6.0      9576775.0
7.0     15273100.0
8.0     12127150.0
9.0      9738900.0
10.0    15954675.0
11.0    12223450.0
12.0    13944575.0
Name: loan_amnt, dtype: float64

In [191]:
loan_1.groupby(['sub_grade']).mean()

id     loan_amnt  loan_amnt_Eur   funded_amnt  \
sub_grade                                                            
1.0        5.572899e+07  13368.245614   12132.952164  13447.807018   
2.0        5.402602e+07  14246.043165   12886.633395  14413.129496   
3.0        5.368352e+07  13105.125523   11873.750323  13130.020921   
4.0        5.278962e+07  14360.835913   13018.540620  14888.080495   
5.0        5.334505e+07  14180.627490   12844.065173  14308.715139   
6.0        5.479998e+07  13705.943026   12403.324447  13786.787819   
7.0        5.434404e+07  13392.988395   12123.830460  13630.560928   
8.0        5.495569e+07  14165.660377   12829.416168  14400.754717   
9.0        5.441008e+07  14002.667269   12684.767649  14080.650995   
10.0       5.459830e+07  12670.344130   11481.438054  12563.562753   
11.0       5.387663e+07  13400.993641   12132.101936  13763.314785   
12.0       5.384824e+07  13836.243386   12502.498365  13509.656085   
13.0       5.457469e+07  14961.177474   13563.665214  14453.754266   
14.0       5.455485e+07  14789.494681   13421.582483  14821.498227   
15.0       5.460645e+07  14345.153664   13005.683226  14177.718676   
16.0       5.283201e+07  14328.452685   12952.249091  14529.028133   
17.0       5.298182e+07  14568.352060   13194.886209  14615.074906   
18.0       5.366536e+07  15230.600000   13783.083544  15237.700000   
19.0       5.407777e+07  15856.862745   14369.347434  15688.431373   
20.0       5.312897e+07  15719.843049   14231.785042  16016.816143   
21.0       5.334357e+07  17645.106383   15995.164871  17965.957447   
22.0       5.357449e+07  15899.074074   14396.717936  15847.376543   
23.0       5.440632e+07  16858.771930   15228.910361  17534.356725   
24.0       5.220577e+07  17477.877698   15791.680178  17816.726619   
25.0       5.393959e+07  18619.298246   16887.587135  17528.947368   
26.0       5.215508e+07  19987.234043   18135.874784  19064.893617   
27.0       5.233452e+07  17806.730769   16072.896711  17232.211538   
28.0       5.378061e+07  18661.029412   16864.002598  18786.029412   
29.0       5.360574e+07  19462.209302   17537.715256  18418.023256   
30.0       5.080219e+07  18925.000000   17071.797479  18187.500000   
31.0       5.175289e+07  20730.263158   18788.515623  22446.052632   
32.0       5.302857e+07  16942.500000   15208.980771  15172.500000   
33.0       5.916880e+07  12325.000000   11438.862462   7075.000000   
34.0       5.339136e+07  18253.571429   16526.315645  20446.428571   
35.0       4.542227e+07  19337.500000   17230.149057  19337.500000   
36.0       5.378115e+07  15028.745136   13610.034731  15046.254864   

           funded_amnt_Eur  int_rate  installment  installment_Eur  \
sub_grade                                                            
1.0           12207.236540  0.060000   402.557298       365.211377   
2.0           13039.861419  0.060000   428.563777       388.005872   
3.0           11910.128417  0.060000   400.169582       362.602203   
4.0           13497.076139  0.060000   449.811362       407.856126   
5.0           12954.750587  0.060000   429.858546       389.300050   
6.0           12475.203918  0.060000   387.780314       350.919148   
7.0           12340.214452  0.060000   391.625919       354.533830   
8.0           13046.509881  0.060000   411.007396       372.497705   
9.0           12754.061084  0.060000   388.798662       352.361192   
10.0          11383.043373  0.060000   367.364008       332.874399   
11.0          12462.538727  0.060000   385.512798       348.975696   
12.0          12216.930907  0.060000   391.473122       354.011458   
13.0          13100.169238  0.128621   418.196502       379.148954   
14.0          13447.092606  0.134760   410.677695       372.586562   
15.0          12847.705386  0.141936   410.293901       371.928274   
16.0          13131.673626  0.151421   416.690153       376.730065   
17.0          13234.581294  0.159635   431.800037       391.211123   
18.0          13791.358653  0.

In [197]:
loan_1.groupby(['sub_grade']).mean().sort_values('loan_amnt', ascending = False)

id     loan_amnt  loan_amnt_Eur   funded_amnt  \
sub_grade                                                            
31.0       5.175289e+07  20730.263158   18788.515623  22446.052632   
26.0       5.215508e+07  19987.234043   18135.874784  19064.893617   
29.0       5.360574e+07  19462.209302   17537.715256  18418.023256   
35.0       4.542227e+07  19337.500000   17230.149057  19337.500000   
30.0       5.080219e+07  18925.000000   17071.797479  18187.500000   
28.0       5.378061e+07  18661.029412   16864.002598  18786.029412   
25.0       5.393959e+07  18619.298246   16887.587135  17528.947368   
34.0       5.339136e+07  18253.571429   16526.315645  20446.428571   
27.0       5.233452e+07  17806.730769   16072.896711  17232.211538   
21.0       5.334357e+07  17645.106383   15995.164871  17965.957447   
24.0       5.220577e+07  17477.877698   15791.680178  17816.726619   
32.0       5.302857e+07  16942.500000   15208.980771  15172.500000   
23.0       5.440632e+07  16858.771930   15228.910361  17534.356725   
22.0       5.357449e+07  15899.074074   14396.717936  15847.376543   
19.0       5.407777e+07  15856.862745   14369.347434  15688.431373   
20.0       5.312897e+07  15719.843049   14231.785042  16016.816143   
18.0       5.366536e+07  15230.600000   13783.083544  15237.700000   
36.0       5.378115e+07  15028.745136   13610.034731  15046.254864   
13.0       5.457469e+07  14961.177474   13563.665214  14453.754266   
14.0       5.455485e+07  14789.494681   13421.582483  14821.498227   
17.0       5.298182e+07  14568.352060   13194.886209  14615.074906   
4.0        5.278962e+07  14360.835913   13018.540620  14888.080495   
15.0       5.460645e+07  14345.153664   13005.683226  14177.718676   
16.0       5.283201e+07  14328.452685   12952.249091  14529.028133   
2.0        5.402602e+07  14246.043165   12886.633395  14413.129496   
5.0        5.334505e+07  14180.627490   12844.065173  14308.715139   
8.0        5.495569e+07  14165.660377   12829.416168  14400.754717   
9.0        5.441008e+07  14002.667269   12684.767649  14080.650995   
12.0       5.384824e+07  13836.243386   12502.498365  13509.656085   
6.0        5.479998e+07  13705.943026   12403.324447  13786.787819   
11.0       5.387663e+07  13400.993641   12132.101936  13763.314785   
7.0        5.434404e+07  13392.988395   12123.830460  13630.560928   
1.0        5.572899e+07  13368.245614   12132.952164  13447.807018   
3.0        5.368352e+07  13105.125523   11873.750323  13130.020921   
10.0       5.459830e+07  12670.344130   11481.438054  12563.562753   
33.0       5.916880e+07  12325.000000   11438.862462   7075.000000   

           funded_amnt_Eur  int_rate  installment  installment_Eur  \
sub_grade                                                            
31.0          20311.000482  0.158500   676.760000       612.413427   
26.0          17285.259300  0.218839   558.362872       506.811585   
29.0          16600.711612  0.236651   584.245581       526.248027   
35.0          17230.149057  0.174950   589.080000       525.009714   
30.0          16408.239231  0.256881   533.572500       481.983959   
28.0          16948.951962  0.187062   571.840882       516.958042   
25.0          15915.130843  0.208292   528.591667       479.843863   
34.0          18518.197500  0.274186   566.650000       512.873888   
27.0          15561.804586  0.227019   490.743077       442.712027   
21.0          16287.682072  0.154194   488.281106       442.703465   
24.0          16097.932314  0.198212   492.452014       444.644558   
32.0          13640.937673  0.267360   528.117000       474.344195   
23.0          15842.684781  0.184737   466.194269       421.091478   
22.0          14352.668625  0.180478   453.154198       410.267728   
19.0          14211.032015  0.168568   443.842118       402.423307   
20.0          14508.251141  0.173338   463.472018       419.612927   
18.0          13791.358653  0.161512   448.024680       405.023402   
36.0          13625.660937  0.

In [199]:
loan_1['int_rate'].max()

0.2899

In [200]:
loan_1['int_rate'].min()

0.06

In [201]:
loan_1.groupby(['term_months']).mean().sort_values('loan_amnt', ascending = False)

id     loan_amnt  loan_amnt_Eur   funded_amnt  \
term_months                                                            
60.0         5.380579e+07  18767.114816   16990.717021  18779.934122   
36.0         5.414016e+07  12068.619647   10932.359224  12117.867378   

             funded_amnt_Eur  int_rate  installment  installment_Eur  \
term_months                                                            
60.0            17003.015549  0.127281   460.521648       416.925819   
36.0            10977.039762  0.087710   396.653589       359.340623   

             total_pymnt  total_pymnt_Eur  exchange_rate  issue_date  \
term_months                                                            
60.0         3332.454044      3004.084305       1.105046    6.642915   
36.0         2781.911694      2507.954975       1.104108    6.634612   

             loan_status  sub_grade  verification_status  addr_state  
term_months                                                           
60.0            0.929282  16.167787             0.740522    2.239581  
36.0            0.932495  11.337207             0.648464    2.192167

In [204]:
loan_1.groupby(['term_months']).sum().sort_values('loan_amnt', ascending = False)

id   loan_amnt  loan_amnt_Eur  funded_amnt  \
term_months                                                         
36.0         3.400544e+11  75803000.0   6.866615e+07   76112325.0   
60.0         2.001037e+11  69794900.0   6.318848e+07   69842575.0   

             funded_amnt_Eur  int_rate  installment  installment_Eur  \
term_months                                                            
36.0            6.894679e+07  550.9090   2491381.19     2.257018e+06   
60.0            6.323421e+07  473.3581   1712680.01     1.550547e+06   

              total_pymnt  total_pymnt_Eur  exchange_rate  issue_date  \
term_months                                                             
36.0         1.747319e+07     1.575247e+07    6934.904230     41672.0   
60.0         1.239340e+07     1.117219e+07    4109.665479     24705.0   

             loan_status  sub_grade  verification_status  addr_state  
term_months                                                           
36.0              5857.0    71209.0               4073.0     13769.0  
60.0              3456.0    60128.0               2754.0      8329.0

In [205]:
loan_1.groupby(['term_months']).count().sort_values('loan_amnt', ascending = False)

id  loan_amnt  loan_amnt_Eur  funded_amnt  funded_amnt_Eur  \
term_months                                                                 
36.0         6281       6281           6281         6281             6281   
60.0         3719       3719           3719         3719             3719   

             int_rate  installment  installment_Eur  total_pymnt  \
term_months                                                        
36.0             6281         6281             6281         6281   
60.0             3719         3719             3719         3719   

             total_pymnt_Eur  exchange_rate  issue_date  loan_status  \
term_months                                                            
36.0                    6281           6281        6281         6281   
60.0                    3719           3719        3719         3719   

             sub_grade  verification_status  addr_state  
term_months                                              
36.0              6281                 6281        6281  
60.0              3719                 3719        3719